/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author dicky
 */
public class mainMenu extends javax.swing.JFrame {

    /**
     * Creates new form mainMenu
     */
    public mainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btnInputData = new javax.swing.JButton();
        btnCariData = new javax.swing.JButton();
        btnEditData = new javax.swing.JButton();
        btnTabelData = new javax.swing.JButton();
        btnExitMenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1058, 787));
        setSize(new java.awt.Dimension(1440, 1024));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(600, 600));
        jPanel3.setLayout(new java.awt.GridLayout(2, 2, 100, 100));

        btnInputData.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnInputData.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/upload (icon).png"))); // NOI18N
        btnInputData.setText("Input Data Mahasiswa");
        btnInputData.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnInputData.setPreferredSize(new java.awt.Dimension(200, 200));
        btnInputData.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnInputData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInputDataActionPerformed(evt);
            }
        });
        jPanel3.add(btnInputData);

        btnCariData.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnCariData.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/searching (icon).png"))); // NOI18N
        btnCariData.setText("Cari Data Mahasiswa");
        btnCariData.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCariData.setPreferredSize(new java.awt.Dimension(200, 200));
        btnCariData.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCariData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariDataActionPerformed(evt);
            }
        });
        jPanel3.add(btnCariData);

        btnEditData.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnEditData.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/draw (icon).png"))); // NOI18N
        btnEditData.setText("Edit Data Mahasiswa");
        btnEditData.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEditData.setPreferredSize(new java.awt.Dimension(200, 200));
        btnEditData.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEditData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditDataActionPerformed(evt);
            }
        });
        jPanel3.add(btnEditData);

        btnTabelData.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnTabelData.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/table (icon).png"))); // NOI18N
        btnTabelData.setText("Tabel Data Mahasiswa");
        btnTabelData.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTabelData.setPreferredSize(new java.awt.Dimension(200, 200));
        btnTabelData.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnTabelData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTabelDataActionPerformed(evt);
            }
        });
        jPanel3.add(btnTabelData);

        btnExitMenu.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnExitMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/check-out (XS icon).png"))); // NOI18N
        btnExitMenu.setText("Keluar");
        btnExitMenu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExitMenu.setPreferredSize(new java.awt.Dimension(100, 100));
        btnExitMenu.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnExitMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(228, Short.MAX_VALUE)
                .addComponent(jPanel3, 568, 568, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(239, 239, 239))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnExitMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jPanel3, 592, 592, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnExitMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(81, 81, 81))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInputDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInputDataActionPerformed
        this.setVisible(false);
        new inputDataMahasiswa().show();
    }//GEN-LAST:event_btnInputDataActionPerformed

    private void btnExitMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitMenuActionPerformed
        this.setVisible(false);
        new login().show();
    }//GEN-LAST:event_btnExitMenuActionPerformed

    private void btnCariDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariDataActionPerformed
        this.setVisible(false);
        new cariData().show();
    }//GEN-LAST:event_btnCariDataActionPerformed

    private void btnEditDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditDataActionPerformed
        this.setVisible(false);
        new editData().show();
    }//GEN-LAST:event_btnEditDataActionPerformed

    private void btnTabelDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTabelDataActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new tabelData().show();
    }//GEN-LAST:event_btnTabelDataActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCariData;
    private javax.swing.JButton btnEditData;
    private javax.swing.JButton btnExitMenu;
    private javax.swing.JButton btnInputData;
    private javax.swing.JButton btnTabelData;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
